name: Java CI with Gradle

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
          google-chrome --version

      - name: Set up OWASP ZAP
        run: |
          docker pull zaproxy/zap-stable
          docker run -u zap -d -p 8090:8090 --name zap zaproxy/zap-stable zap.sh -daemon -host 127.0.0.1 -port 8090 -config api.addrs.addr.regex=true -config api.disablekey=true

      - name: Wait for ZAP to start
        run: sleep 30

      - name: Run tests with Gradle
        run: ./gradlew test -Dscan=false -Dheadless=true
        env:
          CHROME_BIN: /usr/bin/google-chrome
